# Generated by Django 5.0.6 on 2024-05-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='time',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='run',
            old_name='runner',
            new_name='runnerName',
        ),
        migrations.AlterField(
            model_name='run',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='firstName',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='runner',
            name='lastName',
            field=models.CharField(max_length=150),
        ),
    ]
